import { useState, useEffect, useCallback } from 'react';
import { Link } from 'react-router-dom';
import { jobService } from '../services/jobService.js';
import { formatPrice, formatDate } from '../utils/formatters.js';
import Spinner from '../components/common/Spinner.jsx';
import Alert from '../components/common/Alert.jsx';
export default function MyJobsPage() {
  const [jobs, setJobs] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const fetch = useCallback(async () => { setLoading(true); try { setJobs(await jobService.getMyJobs()); } catch (e) { setError(e.message); } finally { setLoading(false); } }, []);
  useEffect(() => { fetch(); }, [fetch]);
  return <main style={{ padding: '40px 0 80px' }}><div className="container"><div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 28 }}><div><h1 style={{ fontSize: 26, fontWeight: 800, marginBottom: 4 }}>Mina jobb</h1><p style={{ color: 'var(--muted)' }}>Hantera dina publicerade jobb.</p></div><Link to="/lagg-upp-jobb" className="btn btn-primary">+ Nytt jobb</Link></div>{error && <Alert type="error" style={{ marginBottom: 20 }}>{error}</Alert>}{loading ? <Spinner /> : jobs.length === 0 ? <div style={{ textAlign: 'center', padding: 60, color: 'var(--muted)' }}><p style={{ fontWeight: 600 }}>Inga jobb annu.</p><Link to="/lagg-upp-jobb" className="btn btn-primary" style={{ marginTop: 16 }}>Lagg upp</Link></div> : <div style={{ display: 'flex', flexDirection: 'column', gap: 14 }}>{jobs.map(j => <div key={j.id} style={{ background: 'var(--white)', borderRadius: 'var(--r)', border: '1px solid var(--border)', padding: '18px 22px', display: 'flex', alignItems: 'center', gap: 16 }}><div style={{ flex: 1 }}><Link to={'/jobs/' + j.id} style={{ fontSize: 15, fontWeight: 700, color: 'var(--dark)' }}>{j.title}</Link><div style={{ display: 'flex', gap: 12, marginTop: 6 }}>{j.location && <span style={{ fontSize: 13, color: 'var(--muted)' }}>📍 {j.location}</span>}<span style={{ fontSize: 13, color: 'var(--muted)' }}>{formatDate(j.created_at)}</span></div></div><div style={{ fontSize: 18, fontWeight: 800, color: 'var(--blue)' }}>{formatPrice(j.price)}</div><button onClick={() => handleDelete(j.id)} style={{ background: 'var(--red-light)', color: 'var(--red)', border: 'none', borderRadius: 8, padding: '7px 14px', fontSize: 13, fontWeight: 600, cursor: 'pointer' }}>Ta bort</button></div>)}</div>}</div></main>;
}
