import { useState, useEffect } from 'react';
import { jobService } from '../../services/jobService.js';
import Spinner from '../common/Spinner.jsx';
export default function JobForm({ initial = {}, onSubmit, loading, totalYear = 0 }) {
  const [form, setForm] = useState({ title: '', description: '', categoryId: '', location: '', price: '', ...initial });
  const [categories, setCategories] = useState([]);
  const [errors, setErrors] = useState({});
  useEffect(() => { jobService.getCategories().then(setCategories).catch(() => {}); }, []);
  const change = (f) => (e) => setForm(p => ({ ...p, [f]: e.target.value }));
  return <form onSubmit={handleSubmit} noValidate><div className="section"><h2 style={{ fontSize: 17, fontWeight: 700, marginBottom: 20 }}>Grundlaggande information</h2><div className="form-group"><label>Jobbtitel *</label><input type="text" maxLength={80} placeholder="t.ex. Grasklippning" value={form.title} onChange={change('title')} style={errors.title ? { borderColor: 'var(--red)' } : {}} />{errors.title && <p className="error">{errors.title}</p>}</div><div className="form-group"><label>Beskrivning *</label><textarea rows={5} placeholder="Beskriv vad som ska goras..." value={form.description} onChange={change('description')} style={errors.description ? { borderColor: 'var(--red)' } : {}} />{errors.description && <p className="error">{errors.description}</p>}</div><div className="form-group"><label>Kategori *</label><select value={form.categoryId} onChange={change('categoryId')} style={errors.categoryId ? { borderColor: 'var(--red)' } : {}}><option value="">Valj kategori...</option>{categories.map(c => <option key={c.id} value={c.id}>{c.icon} {c.name}</option>)}</select>{errors.categoryId && <p className="error">{errors.categoryId}</p>}</div><div className="form-group"><label>Plats</label><input type="text" placeholder="t.ex. Malmo" value={form.location} onChange={change('location')} /></div><div className="form-group"><label>Pris (kr) *</label><input type="number" placeholder="0" min="0" value={form.price} onChange={change('price')} style={errors.price ? { borderColor: 'var(--red)' } : {}} />{errors.price && <p className="error">{errors.price}</p>}</div></div><button type="submit" className="btn btn-primary btn-full btn-lg" disabled={loading}>{loading ? <Spinner size={18} color="#fff" /> : 'Publicera jobb'}</button></form>;
}
